---
title: "APO Project"
author: "Claire Layton"
date: "February 28, 2020"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Load in excel file and make predictor variables factors
library(readxl)
APOProject <- read_excel("~/Design of Experiments/APO Project Dataset.xlsx")
attach(APOProject)
head(APOProject)
Semester = factor(Semester)
Address = factor(Address)
KnewBrother = factor(KnewBrother)
RecruitmentSource = factor(RecruitmentSource)
Scouting = factor(Scouting)
Personality = factor(Personality)
Gender = factor(Gender)
Year = factor(Year)
```

```{r}
#Practice Graphs
#library(dplyr)
#library(ggplot2)
ggplot(aes(x =Year), data = APOProject, color = factor(Year)) +
  geom_bar()

ggplot(APOProject, aes(fill=factor(Gender), x=factor(Personality))) + 
    geom_bar(position="dodge")

ggplot(APOProject, aes(fill=factor(Personality), x=factor(Gender))) + 
     geom_bar(position="fill")

ggplot(APOProject, aes(fill=factor(Accepted), x=factor(Semester))) + 
    geom_bar(position="fill") +
    coord_flip()

ggplot(APOProject, aes(fill=factor(Accepted), x=factor(Gender))) + 
    geom_bar(position="dodge") +
    coord_flip()


ggplot(APOProject, aes(fill=factor(Accepted), x=factor(RecruitmentSource))) + 
    geom_bar(position="dodge") +
    theme_bw() +
    scale_fill_manual(values=c("#0033ab", "#f7b512")) +
    labs( title = "Recruitment Source Popularity",
    x = "Recruitment Source",
    y = "Frequency") 


RecruitmentSource2 <- factor(RecruitmentSource, levels=c("1", "2", "3", "4", "5", "6", "7"), 
                            labels=c("Flyering/Info Booth", "Facebook", "Other Social Media/Online", "Directly from a Brother", "Other Word of Mouth", "Multiple Sources", "Other/Unknown"))
ggplot(APOProject, aes(fill=RecruitmentSource2, x=RecruitmentSource2)) + 
    geom_bar(position="dodge") +
    theme_bw() +
    theme(axis.text.y=element_blank()) +
    facet_wrap(~Semester, ncol = 4) +
    labs( title = "Recruitment Source Popularity",
    x = "Recruitment Source",
    y = "Frequency") +
    scale_fill_discrete(name = "Recruitment Source") +
    coord_flip()


ggplot(APOProject, aes(fill=factor(RecruitmentSource), x=factor(Semester))) + 
    geom_bar(position="fill") +
    coord_flip()



```


```{r}
#Overall Recruitment Source Frequency
RecruitmentSource2 <- factor(RecruitmentSource, levels=c("1", "2", "3", "4", "5", "6", "7"), 
                            labels=c("Flyering/Info Booth", "Facebook", "Other Social Media/Online", 
                                     "Directly from a Brother", "Other Word of Mouth", "Multiple Sources","Other/Unknown"))
ExtendedBid = factor(Accepted, levels = c("0", "1"), labels = c("Denied Bid", "Extended Bid"))
ggplot(APOProject, aes(fill=ExtendedBid, x=RecruitmentSource2)) + 
    geom_bar(position="fill") +
    theme_bw() +
    scale_fill_manual(values=c("#f7b512","#0033ab"), name = "Extended Bid") +
    theme(plot.title = element_text(hjust = 0.5)) +
    labs( title = "Acceptance Rate by Recruitment Source",
    x = "Recruitment Source",
    y = "Proportion of Rushes") +
    
    coord_flip() 
    


ggplot(APOProject, aes(x=RecruitmentSource2)) + 
    geom_bar(position="dodge", fill = "#0033ab") +
    theme_bw() +
    theme(plot.title = element_text(hjust = 0.5)) +
    labs(title = "Recruitment Source Frequency",
    x = "Recruitment Source",
    y = "Number of Rushes") +
    coord_flip()


#Plot of Recruitment Source Frequency by Semester

ggplot(APOProject, aes(fill=RecruitmentSource2, x=RecruitmentSource2)) + 
    geom_bar(position="dodge") +
    theme_bw() +
    theme(axis.text.y=element_blank()) +
    facet_wrap(~Semester, ncol = 4) +
    labs( title = "Recruitment Source Popularity",
    x = "Recruitment Source",
    y = "Frequency") +
    scale_fill_discrete(name = "Recruitment Source") +
    coord_flip()

```



```{r}

ggplot(APOProject, aes(x=RecruitmentSource2)) + 
    geom_bar(position="dodge", fill = "#0033ab") +
    theme_bw() +
    theme(plot.title = element_text(hjust = 0.5)) +
    labs(title = "Recruitment Source Frequency",
    x = "Recruitment Source",
    y = "Number of Rushes") +
    coord_flip()
#Plot of Gender Frequency
ggplot(APOProject, aes(x=GenderForLabels)) + 
    geom_bar(position="dodge", fill = "#0033ab") +
    theme_bw() +
    theme(plot.title = element_text(hjust = 0.5)) +
    labs(title = "Gender Frequency",
    x = "Gender",
    y = "Number of Rushes") 
```






```{r}
#Plot of Gender Frequency
GenderForLabels = factor(Gender, levels = c("2", "1", "3"), labels = c("Female", "Male", "Nonbinary/Unknown"))
ggplot(APOProject, aes(x=GenderForLabels)) + 
    geom_bar(position="dodge", fill = "#0033ab") +
    theme_bw() +
    theme(plot.title = element_text(hjust = 0.5)) +
    labs(title = "Gender Frequency",
    x = "Gender",
    y = "Number of Rushes") 

ggplot(APOProject, aes(fill=ExtendedBid, x=GenderForLabels)) + 
  geom_bar(position="fill")  +
  scale_fill_manual(values=c("#f7b512","#0033ab"), name = "Extended Bid") +
  labs(title = "Acceptance Rate by Gender",
  x = NULL,    
  y = "Proportion Accepted") +
  theme(plot.title = element_text(hjust = 0.5))
  

ggplot(APOProject, aes(fill=RecruitmentSource2, x=RecruitmentSource2)) + 
    geom_bar(position="dodge") +
    theme_bw() +
    theme(axis.text.y=element_blank()) +
    facet_wrap(~Gender, ncol = 3) +
    labs( title = "Recruitment Source Frequency by Gender",
    x = "Recruitment Source",
    y = "Frequency") +
    scale_fill_discrete(name = "Recruitment Source") +
    coord_flip()

ggplot(APOProject, aes(fill=RecruitmentSource2, x=GenderForLabels)) + 
    geom_bar(position="dodge") +
    theme_bw() +
    theme(axis.text.y=element_blank()) +
    #facet_wrap(~Gender, ncol = 3) +
    labs( title = "Recruitment Source Frequency by Gender",
    x = "Recruitment Source",
    y = "Frequency") +
    scale_fill_discrete(name = "Recruitment Source") 

ggplot(APOProject, aes(fill=RecruitmentSource2, x=GenderForLabels)) + 
    geom_bar(position="fill") +
    labs( title = "Recruitment Source Proportion by Gender",
    x = NULL,
    y = "Gender", legend = "Recruitment Source") +
    scale_fill_discrete(name = "Recruitment Source")
    coord_flip()
  
```

```{r}
#Plot of Scouting Involvement
ScoutingForLabels = factor(Scouting, levels = c("1", "2", "3"), labels = c("No Involvement", "Some Involvement", "Eagle or Gold Award"))
ggplot(APOProject, aes(x=ScoutingForLabels)) + 
    geom_bar(position="dodge", fill = "#f7b512") +
    theme_bw() +
    theme(plot.title = element_text(hjust = 0.5)) +
    labs(title = "Scouting Involvement Frequency",
    x = "Scouting Involvement",
    y = "Number of Rushes") 

ggplot(APOProject, aes(fill=ExtendedBid, x=ScoutingForLabels)) + 
  geom_bar(position="fill")  +
  labs(title = "Acceptance Rate by Scouting Involvement",
  x = NULL,    
  y = "Proportion Accepted") +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_fill_discrete(name = NULL)+
  scale_fill_manual(values=c("#f7b512","#0033ab"), name = "Extended Bid") 
```

```{r}
#Plot of Brother Connection
KnewBrotherForLabels = factor(KnewBrother, levels = c("1", "2", "3"), labels = c("Did Not Know a Brother", "Knew a Brother", "Unknown"))
ggplot(APOProject, aes(x=KnewBrotherForLabels)) + 
    geom_bar(position="dodge", fill = "#0033ab") +
    theme_bw() +
    theme(plot.title = element_text(hjust = 0.5)) +
    labs(title = "Previous Brother Connection Frequency",
    x = "Connection to Brother",
    y = "Number of Rushes") 

ggplot(APOProject, aes(fill=ExtendedBid, x=KnewBrotherForLabels)) + 
  geom_bar(position="fill")  +
  labs(title = "Acceptance Rate by Previous Brother Connection",
  x = NULL,    
  y = "Proportion Accepted") +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_fill_discrete(name = NULL)+
  scale_fill_manual(values=c("#f7b512","#0033ab"), name = "Extended Bid") 
```

```{r}
#Plot of Address Frequency
AddressForLabels = factor(Address, levels = c("1", "2", "3"), labels = c("On-campus", "Off-campus", "Unknown"))
ggplot(APOProject, aes(x=AddressForLabels)) + 
    geom_bar(position="dodge", fill = "#0033ab") +
    theme_bw() +
    theme(plot.title = element_text(hjust = 0.5)) +
    labs(title = "Address Frequency",
    x = "Location of Address",
    y = "Number of Rushes") 

ggplot(APOProject, aes(fill=ExtendedBid, x=AddressForLabels)) + 
  geom_bar(position="fill")  +
  labs(title = "Acceptance Rate by Address",
  x = NULL,    
  y = "Proportion Accepted") +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_fill_discrete(name = NULL)+
  scale_fill_manual(values=c("#f7b512","#0033ab"), name = "Extended Bid")
```

```{r}
#Plot of Personality Frequency
PersonalityForLabels = factor(Personality, levels = c("1", "2", "3", "4"), 
                              labels = c("Introverted/Shy", "Ambivert/Mix", "Extroverted/Outgoing", "Uncategorized/Unknown"))

ggplot(APOProject, aes(x=PersonalityForLabels)) + 
    geom_bar(position="dodge", fill = "#f7b512") +
    theme_bw() +
    theme(plot.title = element_text(hjust = 0.5)) +
    labs(title = "Personality Frequency",
    x = "Self-Described Personality",
    y = "Number of Rushes") 

ggplot(APOProject, aes(fill=ExtendedBid, x=PersonalityForLabels)) + 
  geom_bar(position="fill")  +
  labs(title = "Acceptance Rate by Self-Described Personality",
  x = NULL,    
  y = "Proportion Accepted") +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_fill_discrete(name = NULL)+
  scale_fill_manual(values=c("#f7b512","#0033ab"), name = "Extended Bid")
```

```{r}
#Plot of Year Frequency
YearForLabels = factor(Year, levels = c("1", "2", "3", "4", "5", "0"), 
                              labels = c("1", "2", "3", "4", "5+", "Unknown"))

ggplot(APOProject, aes(x=YearForLabels)) + 
    geom_bar(position="dodge", fill = "#f7b512") +
    theme_bw() +
    theme(plot.title = element_text(hjust = 0.5)) +
    labs(title = "Year in School Frequency",
    x = "Year in School",
    y = "Number of Rushes") 

ggplot(APOProject, aes(fill=ExtendedBid, x=YearForLabels)) + 
  geom_bar(position="fill")  +
  labs(title = "Acceptance Rate by Year in School",
  x = NULL,    
  y = "Proportion Accepted") +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_fill_discrete(name = NULL)+
  scale_fill_manual(values=c("#f7b512","#0033ab"), name = "Extended Bid")
```

```{r}
#Plot of Acceptance Rate by Semester - Need to fix legend title
SemesterForLabels <- factor(Semester, levels=c("F16", "S17", "F17", "S18", "F18", "S19", "F19", "S20"), 
                            labels=c("F16", "S17", "F17", "S18", "F18", "S19", "F19", "S20"))
ExtendedBid = factor(Accepted, levels = c("0", "1"), labels = c("Denied Bid", "Extended Bid"))

ggplot(APOProject, aes(x=SemesterForLabels)) + 
    geom_bar(position="dodge", fill = "#f7b512") +
    theme_bw() +
    theme(plot.title = element_text(hjust = 0.5)) +
    labs(title = "Semester Frequency",
    x = "Semester Rushed",
    y = "Number of Rushes") 


ggplot(APOProject, aes(fill=ExtendedBid, x=SemesterForLabels)) + 
  geom_bar(position="fill")  +
  labs(title = "Acceptance Rate by Semester",
  x = NULL,    
  y = "Proportion Accepted") +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_fill_discrete(name = NULL)+
  scale_fill_manual(values=c("#f7b512","#0033ab"), name = "Extended Bid")
```

```{r}
ggplot(APOProject, aes(fill=ExtendedBid, x=ScoutingForLabels)) + 
  geom_bar(position="fill")  +
  labs(title = "Acceptance Rate by Scouting Involvement",
  x = NULL,    
  y = "Proportion Accepted") +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_fill_discrete(name = NULL)+
  scale_fill_manual(values=c("#f7b512","#0033ab"), name = "Extended Bid")
```

```{r}
###SEE BoTTOM OF PAGE 27 Class Notes


#LM = aov(Accepted ~ Semester*Address*Gender*KnewBrother*Personality*RecruitmentSource*Scouting)
#anova(LM)
#LMreduced = aov(Accepted ~ Semester+Address+Gender+KnewBrother+Personality+RecruitmentSource+Scouting)
#anova(LMreduced)
#LM = lm(Accepted ~ Semester*Address*Gender*KnewBrother*Personality*RecruitmentSource*Scouting)
#anova(LM)
Year = factor(Year)

LMsimple = lm(Accepted ~ Semester)
summary(LMsimple)
anova(LMsimple)

```





```{r}
#Logistic Regression Full Model and testing assumptions
#To change base groups for categorical variables use: Year = relevel(Year, "1")
logisticFullModel = glm(Accepted ~ Semester+Address+Gender+KnewBrother+Personality+RecruitmentSource+Scouting+Year, family = binomial(link = "logit"))
summary(logisticFullModel)


#Testing for multicolinearity
#install.packages("car")
#library(car)

vif(logisticFullModel)


#AIC Backwards Elimination to Determine Reduced Model
drop1(logisticFullModel,test="LRT") #iterate this one, keep dropping
stepAIC(logisticFullModel,scope=list(upper=~Semester+Address+Gender+KnewBrother+Personality+RecruitmentSource+Scouting+Year,lower=~1),direction="backward")

stepAIC(logisticFullModel,scope=list(upper=~Semester+Address+Gender+KnewBrother+Personality+RecruitmentSource+Scouting+Year,lower=~1),direction="both")

```


```{r}
#Reduced Model 
logisticReducedModel = glm(formula = Accepted ~ Semester + KnewBrother + 
                             Personality + Year, family = binomial(link = "logit"))
summary(logisticReducedModel)


x <- summary(logisticReducedModel)$coefficients[,1]
cbind(coef_log_odds = x, coef_prob = 1 / (1 + exp(-(x-2.31))))

#to convert log odds to odds ratio use exp(log odds)
exp(-(-2.31))
#  1/(odds) = probability
1/ (1+10.07442)
```


